uploads = []
outputs = []

[[generated]]
id = "BmyMtGMvWz2R4RcMYfSoC"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "yourradar app icon"

[[generated]]
id = "dJcIRJEpzQL9b9SCWfhne"
uri = "file://artifacts/mobile/assets/images/logo-mark.png"
type = "image"
title = "yourradar logo mark transparent"
